apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

helmCharts:
- name: velero
  namespace: velero
  includeCRDs: true
  releaseName: velero
  version: 11.1.1
  repo: https://vmware-tanzu.github.io/helm-charts
  valuesFile: values.yaml
