apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
- name: loki-stack
  namespace: monitoring
  includeCRDs: false
  releaseName: loki-stack
  version: 2.10.3
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
